PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX biopax3: <http://www.biopax.org/release/biopax-level3.owl#>

SELECT DISTINCT ?pathwayID ?pathwayName
WHERE
{
	?pathwayID rdf:type biopax3:Pathway .
	?pathwayID biopax3:displayName ?pathwayName
}
